
### CREAR BEBIDA
POST http://localhost:3000/api/liquids
content-type: application/json

{
    "Nombre": "Wakardi",
    "Tamanio": 750,
    "URL": "https://randomuser.me/api/portraits/women/20.jpg",
    "IDPertenenciaUsuario": 1
}

### ELIMINAR USUARIO
DELETE http://localhost:3000/api/users
content-type: application/json

{
    "Nombre": "Gupilio",
    "Apellido": "Gopez",
    "Correo": "correo@email.com",
    "Contrasenia": "wenas",
    "Date": "2016-01-01",
    "Sexo": "M",
    "UID": 1,
    "_id": "637f7f87ca4acd86bfe77369"
}


### --------------------------------------------------------------
### CREAR USUARIO CON CAMPOS COMPLETOS
POST http://localhost:3000/api/users
content-type: application/json

{
    "Nombre": "Cinthya",
    "Apellido": "González",
    "Correo": "cg@email.com",
    "Contrasenia": "123456",
    "Nacimiento": "2002-01-01",
    "Actividad": "MEDIA",
    "Region": "TEMPLADA",
    "Peso": 60,
    "Estatura": 168,
    "Sexo": "M",
    "StatsData": true,
    "UrlPicture": ""
}

### Debe arrojar error porque faltan elementos
POST http://localhost:3000/api/users
content-type: application/json

{
    "Nombre": "Arnoldo",
    "Apellido": "Ramírez",
    "Correo": "",
    "Nacimiento": "1998-01-01",
    "Actividad": "",
    "Region": "TEMPLADA",
    "Sexo": "M",
    "StatsData": true,
    "UrlPicture": ""
}

