### CREAR ADMIN
POST http://localhost:3000/api/users/register
content-type: application/json

{
    "Nombre": "ADMIN",
    "Apellido": "aaaa",
    "Correo": "adm@capi.com",
    "Contrasenia": "admin123",
    "Nacimiento": "2000-01-01",
    "Actividad": "BAJA",
    "Region": "TEMPLADA",
    "Peso": 1,
    "Estatura": 1,
    "Sexo": "M",
    "StatsData": true,
    "UrlPicture": ""
}

### Obtener token del admin
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "Correo": "adm@capi.com",
    "Contrasenia": "admin123"
}

### FILTRAR USUARIOS CON ADMIN
GET http://localhost:3000/api/admin/search?nombre=Cinthya
content-type: application/json
x-user-token: admintoken

### FILTRAR USUARIOS CON ADMIN TOKEN INCORRECTO (no deja)
GET http://localhost:3000/api/admin/search?nombre=k
content-type: application/json
x-user-token: zLGr2M1yA2-6382a29df4fc17346a204c1f

### FILTRAR USUARIOS CON ID
GET http://localhost:3000/api/admin/search?id=6382a29df4fc17346a204c1f
content-type: application/json
x-user-token: admintoken

### ELIMINAR USUARIO COMO ADMIN
DELETE http://localhost:3000/api/admin/deleteuser?id=6383989ccbebeaa528811626
content-type: application/json
x-user-token: admintoken


### CREAR BEBIDA DEFAULT
POST http://localhost:3000/api/admin/addliquid
content-type: application/json
x-user-token: admintoken

{
    "Nombre": "Electrolit",
    "Cantidad": 400,
    "URL": "https://res.cloudinary.com/walmart-labs/image/upload/d_default.jpg/w_960,dpr_auto,f_auto,q_auto:best/gr/images/product-images/img_large/00750112511856L.jpg"
}

### CREAR BEBIDA DEFAULT
POST http://localhost:3000/api/admin/addliquid
content-type: application/json
x-user-token: admintoken

{
    "Nombre": "Agua natural",
    "Cantidad": 600,
    "URL": "../IMAGES/agua.jpg"
}

### CREAR BEBIDA DEFAULT
POST http://localhost:3000/api/admin/addliquid
content-type: application/json
x-user-token: admintoken

{
    "Nombre": "Café",
    "Cantidad": 250,
    "URL": "../IMAGES/cafe.jpg"
}


### BORRAR BEBIDA DEFAULT
DELETE http://localhost:3000/api/admin/deleteliquid?id=6383be9c5223e259cd5ab060
content-type: application/json
x-user-token: admintoken


### ----------------------------------------------------------------------------------------

### --------------------------------------------------------------
### CREAR USUARIO CON CAMPOS COMPLETOS
POST http://localhost:3000/api/users/register
content-type: application/json

{
    "Nombre": "Cinthya",
    "Apellido": "González",
    "Correo": "cg@email.com",
    "Contrasenia": "123456",
    "Nacimiento": "2002-01-01",
    "Actividad": "MEDIA",
    "Region": "TEMPLADA",
    "Peso": 60,
    "Estatura": 168,
    "Sexo": "M",
    "StatsData": true,
    "UrlPicture": ""
}

### REGISTRAR USUARIO
POST http://localhost:3000/api/users/register
content-type: application/json

{
    "Nombre": "Gupilio",
    "Apellido": "Gopez",
    "Correo": "kiw@gmail.com",
    "Contrasenia": "kiw2",
    "Nacimiento": "2016-01-05",
    "Actividad": "BAJA",
    "Region": "TEMPLADA",
    "Peso": 11,
    "Estatura": 80,
    "Sexo": "H",
    "StatsData": true,
    "UrlPicture": ""
}

###  REGISTRAR USUARIO
POST http://localhost:3000/api/users/register
content-type: application/json

{
    "Nombre": "Carlos",
    "Apellido": "Ponce",
    "Correo": "charles@gmail.com",
    "Contrasenia": "mariobros",
    "Nacimiento": "2001-12-29",
    "Actividad": "BAJA",
    "Region": "TEMPLADA",
    "Peso": 70,
    "Estatura": 188,
    "Sexo": "H",
    "StatsData": true,
    "UrlPicture": ""
}

### REGISTRAR USUARIO
POST http://localhost:3000/api/users/register
content-type: application/json

{
    "Nombre": "Iker",
    "Apellido": "Johannsen",
    "Correo": "ijk@gmail.com",
    "Contrasenia": "bab4s",
    "Nacimiento": "1999-08-02",
    "Actividad": "MEDIA",
    "Region": "CALUROSA",
    "Peso": 75,
    "Estatura": 184,
    "Sexo": "H",
    "StatsData": true,
    "UrlPicture": ""
}

### REGISTRAR USUARIO
POST http://localhost:3000/api/users/register
content-type: application/json

{
    "Nombre": "Jorge",
    "Apellido": "Tovar",
    "Correo": "jorget@gmail.com",
    "Contrasenia": "batman",
    "Nacimiento": "1998-08-01",
    "Actividad": "MEDIA",
    "Region": "TEMPLADA",
    "Peso": 80,
    "Estatura": 171,
    "Sexo": "H",
    "StatsData": true,
    "UrlPicture": ""
}

### INICIAR SESION CON TOKEN
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "Correo": "jorget@gmail.com",
    "Contrasenia": "batman"
}

### INICIAR SESION CON TOKEN
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "Correo": "kiw@gmail.com",
    "Contrasenia": "kiw2"
}

### INICIAR SESION CON TOKEN
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "Correo": "charles@gmail.com",
    "Contrasenia": "mariobros"
}

### INICIAR SESION CON TOKEN
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "Correo": "cg@email.com",
    "Contrasenia": "123456"
}

### INICIAR SESION CON TOKEN
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "Correo": "ikj2@email.com",
    "Contrasenia": "b4b4sas"
}

###  EDITAR USUARIO CON TOKEN (no debe contener todos los campos obligatoriamente)
PUT http://localhost:3000/api/users/edit?id=6383c1b31bb58ae59ebb57f4
content-type: application/json
x-user-token: 9Y3eO7l5hd-6383c1b31bb58ae59ebb57f4

{
    "Nombre": "Carlos",
    "Correo": "mariobros@gmail.com",
    "Contrasenia": "Kingboo",
    "Region": "FRIA"
}

###
PUT http://localhost:3000/api/users/edit?id=6383989ccbebeaa528811626
content-type: application/json
x-user-token: qUCrbme4cT-6383989ccbebeaa528811626

{
    "Nombre": "Kiker",
    "Apellido": "Johannsen",
    "Correo": "ikrj@email.com",
    "Contrasenia": "b4b4sas",
    "Nacimiento": "1999-09-09",
    "Actividad": "MEDIA",
    "Region": "CALUROSA",
    "Peso": 75,
    "Estatura": 183,
    "Sexo": "H",
    "StatsData": true
}


